[theme]
primaryColor = "#f7f7f7"  # light gray
backgroundColor = "#f0f0f0"  # light gray
secondaryBackgroundColor = "#e5e5e5"  # light gray
textColor = "#000000"  # black

[client]
showSidebarNavigation = false
