[server]
headless = false
enableCORS = false
maxMessageSize = 100

[runner]
installCmd = "pip install streamlit"

[browser]
gatherUsageStats = true

[logger]
level = "INFO"
format = "%(asctime)s %(levelname)s %(message)s"

[deprecation]
showDeprecationWarnings = true

[navigation]
hideNavigationBar = true
